# Generated by Django 5.0.4 on 2024-06-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_itembase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBase',
        ),
    ]
